apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-170814627
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-170814627
    app.kubernetes.io/part-of: test-app-170814627
  name: go-170814627
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: go-170814627
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: go-170814627
    spec:
      containers:
      - env:
        - name: TEST_ENV_VAR
          value: Test go app
        image: quay.io/hacdev/4iwibfhb-tenant/test-app-170814627/go-170814627@sha256:bfd9c9ce6862691c3a4aa65c8197b2399740ec3fade6cfc788b45faf78da3d4b
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
