apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: go-170814627
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/hacdev/4iwibfhb-tenant/test-app-170814627/go-170814627@sha256:bfd9c9ce6862691c3a4aa65c8197b2399740ec3fade6cfc788b45faf78da3d4b
        name: my-go
        resources: {}
status: {}
